extends RefCounted
class_name UiText


static func t(key: String) -> String:
	return STRINGS.get(key, key)


const STRINGS := {
	"gold": "金币",
	"lives": "生命",
	"wave": "波次",
	"towers": "塔",
	"next_preview": "下一波预告",
	"now_wave": "当前波次",
	"timer": "下一波倒计时",
	"early_hint": "空格可提前,剩余时间转奖金",
	"map": "地图",
	"hint_controls": "选塔后左键放置迷宫 | 空格开波 | P暂停 | F加速 | 右键取消选中",
	"locked": "该塔尚未解锁",
	"no_gold": "金币不足(需要 %d)",
	"tower_cap": "已达塔数量上限 %d",
	"bad_cell": "不能放这里(会堵死出路或格子无效)",
	"placed": "已放置 %s(-%d)",
	"upgrade": "升级(%d金)",
	"max_lv": "已满级",
	"sell": "出售(+%d金)",
	"upgraded": "升级完成",
	"tech": "科技突破(+1级上限)(%d金)",
	"tech_done": "已突破(最高等级+1)",
	"tech_ok": "科技突破成功!该塔种最高等级+1",
	"sold": "已出售,返还 %d 金",
	"early_wave": "提前开波!奖金 +%d | 第 %d 波",
	"wave_in": "第 %d 波来袭!",
	"can_early": "可空格提前开下一波拿奖金,或继续布防",
	"cleared": "清空!可继续布局,或开下一波",
	"win": "胜利!守住了 %d 波(%s / %s)\n点击或空格重新开始",
	"lose": "失败,第 %d/%s 波基地失守\n点击或空格重新开始",
	"inf": "无穷",
	"resume": "继续 (P)",
	"pause": "暂停 (P)",
	"paused": "已暂停",
	"running": "继续游戏",
	"speed": "速度 x%.0f (F)",
	"start_btn": "开波/提前 (空格)",
	"title": "迷你塔防 - 选择地图与难度",
	"map_line": "地图线路",
	"diff": "难度",
	"easy": "简单",
	"normal": "普通",
	"hard": "困难",
	"diff_fmt": "%s | 金%d 命%d 上限%d塔 %d波",
	"tower_btn": "%s\n%d金",
	"gold_fmt": "金币: %d",
	"lives_fmt": "生命: %d",
	"wave_fmt": "波次: %d / %s",
	"towers_fmt": "塔: %d / %d",
	"lv": "等级%d/%d",
	"target_air_only": "目标:仅飞行单位",
	"target_ground_only": "目标:仅地面单位",
	"target_both": "目标:地面+飞行",
	"pierce": "破甲 %.0f",
	"splash": "溅射半径 %.0f (%.0f%%)",
	"slow": "减速 %.0f%% / %.1fs",
	"poison": "毒素 %.1f/秒 / %.1fs",
	"crit": "暴击 %.0f%% x%.1f",
	"vs": "对空x%.1f 对地x%.1f",
	"dmg_line": "伤害 %.0f | 射程 %.0f | 间隔 %.2fs",
	"map_cross": "横断平原",
	"map_corner": "角落突袭",
	"map_vertical": "纵向通道",
	"map_diagonal": "斜线围城",
	"map_twin": "双岔峡谷",
	"map_canyon": "峡谷冲刺",
	"map_river": "河湾断桥",
	"t_basic": "弹丸塔",
	"t_basic_d": "便宜,适合铺迷宫(无法攻击飞行)",
	"t_splash": "溅射塔",
	"t_splash_d": "范围伤害,克制密集怪(无法攻击飞行)",
	"t_slow": "减速塔",
	"t_slow_d": "减速地面敌人(无法攻击飞行)",
	"t_poison": "毒塔",
	"t_poison_d": "附着毒素持续掉血,可打飞行,溅射也能上毒",
	"t_sniper": "狙击塔",
	"t_sniper_d": "高伤破甲,可打飞行",
	"t_aa": "防空塔",
	"t_aa_d": "只攻击飞行单位,对空特化",
	"e_normal": "普通怪",
	"e_fast": "疾行怪",
	"e_armor": "装甲怪",
	"e_fly": "飞行怪",
	"e_swarm": "虫群",
	"e_split": "分裂怪",
	"e_boss": "首领",
	"diff_easy": "简单",
	"diff_normal": "普通",
	"diff_hard": "困难",
}
